services:
  db:
    image: postgres:17.2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - mydb-data:/var/lib/postgresql/data/pgdata
volumes:
  mydb-data: